services:
  - docker

before_install:
  - sudo add-apt-repository -y ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get install -y ansible
  - sudo service ssh stop
  - build/prepare-build.sh

script:
  - make test