---
  - name: Ensure OS is supported
    fail:
      msg: "Only Ubuntu or Debian is supported."
    when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'

  - name: Ensure OS version is supported
    fail:
      msg: "Only Ubuntu 14.04 or higer."
    when: ansible_distribution_version < '14.04'

  - name: Ensure fresh APT cache
    apt:
      update_cache: yes

  - name: Install wget
    apt: name=wget state=present
    become_user: yes