fpm_socket_dir: "/var/run/php"

fpm_pools:
  -
    name: "{{ app_name }}-1"
    listen: "{{ fpm_socket_dir }}/php-fpm-{{ app_name }}-1.socket"
  -
    name: "{{ app_name }}-2"
    listen: "{{ fpm_socket_dir }}/php-fpm-{{ app_name }}-2.socket"
  -
    name: "{{ app_name }}-3"
    listen: "{{ fpm_socket_dir }}/php-fpm-{{ app_name }}-3.socket"
  -
    name: "{{ app_name }}-4"
    listen: "{{ fpm_socket_dir }}/php-fpm-{{ app_name }}-4.socket"
  -
    name: "{{ app_name }}-5"
    listen: "{{ fpm_socket_dir }}/php-fpm-{{ app_name }}-5.socket"
  -
    name: "{{ app_name }}-6"
    listen: "{{ fpm_socket_dir }}/php-fpm-{{ app_name }}-6.socket"
  -
    name: "{{ app_name }}-7"
    listen: "{{ fpm_socket_dir }}/php-fpm-{{ app_name }}-7.socket"
  -
    name: "{{ app_name }}-8"
    listen: "{{ fpm_socket_dir }}/php-fpm-{{ app_name }}-8.socket"
  -
    name: "{{ app_name }}-9"
    listen: "{{ fpm_socket_dir }}/php-fpm-{{ app_name }}-9.socket"
  -
    name: "{{ app_name }}-10"
    listen: "{{ fpm_socket_dir }}/php-fpm-{{ app_name }}-10.socket"

pm: static
pm_max_children: 100
pm_start_servers: 4
pm_min_spare_servers: 4
pm_max_spare_servers: 8
pm_process_idle_timeout: 10s