---
  - name: Ensure fresh APT cache
    apt:
      update_cache: yes

  - name: Install required software
    apt: name={{ item }} state=present
    become_user: yes
    with_items:
      - php7.0
      - php7.0-zip
      - php7.0-mbstring
      - php7.0-xml